apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-nginx
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: nginx
    targetRevision: 22.3.9
    helm:
      valueFiles:
        - $values/apps/demo-nginx/values.yaml

  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      chart: nginx
      targetRevision: 22.3.9
      helm:
        valueFiles:
          - $values/apps/demo-nginx/values.yaml
    - repoURL: https://github.com/Rsln-git/infra.git
      targetRevision: main
      ref: values


  destination:
    server: https://kubernetes.default.svc
    namespace: demo

  ignoreDifferences:
    - kind: Secret
      name: demo-nginx-tls
      namespace: demo
      jsonPointers:
        - /data
        - /stringData
        - /metadata/annotations

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
